name = "CDRP Chicanery 2.0"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ff7d5cd77be75ad4b1de251caa8290f899ef0f0754d8a3af5b69ef42e261822"

[versions]
minecraft = "1.19.2"
quilt = "0.26.3"
