name = "CDRP Chicanery 2.0"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfff87f30746d63d78dd384fc3e44b6018511f6f2cba3cc33160cbf89d509a3b"

[versions]
minecraft = "1.19.2"
quilt = "0.26.3"
