name = "CDRP Chicanery 2.0"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a08b8f99af316bdb67dee20789cae33e15dcf9647d87644d03a6355a79e9a835"

[versions]
minecraft = "1.19.2"
quilt = "0.26.3"
