name = "CDRP Chicanery 2.0"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f6b788d89bb68ddebb59f67598c606931369b4812fd974c10bb245a97255c87"

[versions]
minecraft = "1.19.2"
quilt = "0.26.3"
