name = "CDRP Chicanery 2.0"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6e1f3e5ce877fc268fec31e2b63a4b961f3888b9c7a36139a70518f97480ea7"

[versions]
minecraft = "1.19.2"
quilt = "0.26.3"
