name = "CDRP Chicanery 2.0"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "577d181d4b025f4aaced66274f364ad4046c7899244e65fa67a96b12e06c00fe"

[versions]
minecraft = "1.19.2"
quilt = "0.26.3"
