name = "CDRP Chicanery 2.0"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba989733c9dbff0d16b18138fdc42ce09237be90b4588bd84199d4ed2a6640ff"

[versions]
minecraft = "1.19.2"
quilt = "0.26.3"
