name = "CDRP Chicanery 2.0"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "269aa9bbd384aeda26746dd2d24cbf78964b8e144f148b48d40d02b187c991d8"

[versions]
minecraft = "1.19.2"
quilt = "0.26.3"
