name = "CDRP Chicanery 2.0"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2d4eb1adbbb254bfd75049400422ebdef9e58827806278e502fa43bea280cfa"

[versions]
minecraft = "1.19.2"
quilt = "0.26.3"
