name = "CDRP Chicanery 2.0"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a55fdbfcc5c13dd60998b617df1abf4ef5efd68aeb464e0eac45b23986c6e444"

[versions]
minecraft = "1.19.2"
quilt = "0.26.3"
