name = "CDRP Chicanery 2.0"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81ff4e14c7db3fa6d379d7770d3b27d6aee973ca91d051f3e0f82cad448508e3"

[versions]
minecraft = "1.19.2"
quilt = "0.26.3"
