name = "CDRP Chicanery 2.0"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d86cc198b6f2d8f0a9b5ce284807d3909867bf7aa615d6d39cd51a4a278da0f1"

[versions]
minecraft = "1.19.2"
quilt = "0.26.3"
