name = "CDRP Chicanery 2.0"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2232cdb13f42cf5b5a78cb2a360d6c44e830c05674e356a4d58c84a621e45b36"

[versions]
minecraft = "1.19.2"
quilt = "0.26.3"
