name = "CDRP Chicanery 2.0"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0143ff84b48e152941ed7a81f49f040c15dd6bcfe541839b93c92fb85fc4f64c"

[versions]
minecraft = "1.19.2"
quilt = "0.26.3"
