name = "CDRP Chicanery 2.0"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2db7b8fab5bc9adbb0edbfc6a7e3371cfe14fba0d5118a1c5064247444a21faf"

[versions]
minecraft = "1.19.2"
quilt = "0.26.3"
