# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				axolotl = true
				bee = true
				cow = true
				pig = true
				skeleton = true
				bat = true
				zombified_piglin = true
				piglin = true
				zombie = true
				drowned = true
				sheep = true
				player = true
				item = true
				turtle = true
				wolf = true
				salmon = true
				zombie_villager = true
				strider = true
				horse = true
				witch = true
				glow_squid = true
				cod = true
				glow_item_frame = false
				squid = true
				spider = true
				creeper = true
				enderman = true
				phantom = true
				slime = true
				villager = true
				item_frame = true
				warden = true
				piglin_brute = true
				trader_llama = true
				lightning_bolt = true

			[light_sources.settings.entities.immersive_portals]
				nether_portal_new = true
				loading_indicator = true
				portal = true

			[light_sources.settings.entities.vinery]
				wandering_winemaker = true
				mule = true

			[light_sources.settings.entities.meadow]
				cream_cow = true
				inky_sheep = true
				pinto_cow = true
				patched_sheep = true

			[light_sources.settings.entities.artifacts]
				mimic = true

